"""add unique constraint on product name and category

Revision ID: baa31573d203
Revises: 5c5d40852b46
Create Date: 2026-04-08 16:27:53.252356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baa31573d203'
down_revision = '5c5d40852b46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_product_name_category', ['name', 'category_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint('uq_product_name_category', type_='unique')

    # ### end Alembic commands ###
